name: MapFramePlayer
main: me.example.mapframeplayer.MapFramePlayer
version: 1.0.0
api-version: '1.20'
commands:
  mplay:
    description: Play JSON frames on map walls
    usage: /mplay
permissions:
  mplay.use:
    default: op
